NavbarToggleNavigation: Переключить навигацию
NavbarHomeLink:         Домой
NavbarPublications:     Публикации

FormSubmitAdd:    Добавить
FormSubmitUpdate: Обновить

HomeHello: Добро пожаловать на сайт русскоязычного сообщества Haskell-разработчиков! Наше желание — использовать этот прекрасный язык, а не просто разговаривать о нём. Наше стремление — объединить всех хаскелистов, говорящих по-русски. Наша цель — увеличить долю использования Haskell в России.

BlogPosts:          Статьи
BlogPostLatest:     Последние статьи
BlogPostAll:        Все статьи
BlogPostAdd:        Добавить статью
BlogPostCategory:   Категория
BlogPostTitle:      Заголовок
BlogPostContent:    Содержание
BlogPostTags:       Теги
BlogPostWasAdded:   Статья успешно добавлена
BlogPostWasUpdated: Статья успешно обновлена

Categories:  Категории
CategoryAdd: Добавить категорию

Tags:   Теги
TagAdd: Добавить тег

UserLogin:  Войти
UserLogout: Выйти
