NavbarToggleNavigation: Переключить навигацию
NavbarHomeLink:         Домой
NavbarPublications:     Публикации

HomeHello: Добро пожаловать на сайт русскоязычного сообщества Haskell-разработчиков! Наше желание — использовать этот прекрасный язык, а не просто разговаривать о нём. Наше стремление — объединить всех хаскелистов, говорящих по-русски. Наша цель — увеличить долю использования Haskell в России.

BlogPosts:      Статьи
BlogPostLatest: Последние статьи
BlogPostAll:    Все статьи
BlogPostAdd:    Добавить статью

Categories:  Категории
CategoryAdd: Добавить категорию

Tags:   Теги
TagAdd: Добавить тег

UserLogin:  Войти
UserLogout: Выйти
