NavbarToggleNavigation: Переключить навигацию
NavbarHomeLink:         Домой
NavbarPublications:     Публикации

FormSubmitAdd:    Добавить
FormSubmitUpdate: Обновить

HomeHello: Добро пожаловать на сайт русскоязычного сообщества Haskell-разработчиков! Наше желание — использовать этот прекрасный язык, а не просто разговаривать о нём. Наше стремление — объединить всех хаскелистов, говорящих по-русски. Наша цель — увеличить долю использования Haskell в России.

BlogPosts:          Статьи
BlogPostLatest:     Последние статьи
BlogPostAll:        Все статьи
BlogPostAdd:        Добавить статью
BlogPostCategory:   Категория
BlogPostTitle:      Заголовок
BlogPostContent:    Содержание
BlogPostDraft:      Черновик
BlogPostTags:       Теги
BlogPostWasAdded:   Статья успешно добавлена
BlogPostWasUpdated: Статья успешно обновлена

Categories:            Категории
CategoryAdd:           Добавить категорию
CategoryTitle:         Заголовок
CategoryWasAdded:      Категория успешно добавлена
CategoryWasUpdated:    Категория успешно обновлена
CategoryAlreadyExists: Такая категория уже существует

Tags:             Теги
TagAdd:           Добавить тег
TagTitle:         Заголовок
TagWasAdded:      Тег успешно добавлен
TagWasUpdated:    Тег успешно обновлён
TagAlreadyExists: Такой тег уже существует

AuthLogin:      Войти
AuthLogout:     Выйти
AuthNotAnAdmin: Для этого действия нужны администраторские права

Users:                  Пользователи
UserAdd:                Добавить пользователя
UserIdent:              Github ident
UserName:               Имя
UserAvatarUrl:          Веб-адресс картинки
UserAdmin:              Администратор
UserWasAdded:           Пользователь успешно добавлен
UserWasUpdated:         Пользователь успешно обновлён
UserIdentAlreadyExists: Пользователь с таким ident уже существует
UserNameAlreadyExists:  Пользователь с таким именем уже существует
