static-dir:       "static"
host:             "*4"
port:             "_env:PORT:3000"
approot:          "http://ruhaskell.herokuapp.com"
ip-from-header:   false

heroku:           true

development:      false
detailed-logging: true
should-log-all:   true
reload-templates: false
mutable-static:   false
skip-combining:   false

database:
  user:     "_env:PGUSER:pg_user"
  password: "_env:PGPASS:pg_pass"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:pg_name"
  poolsize: "_env:PGPOOLSIZE:10"
